# Generated by Django 3.2.3 on 2021-07-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDE', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=70)),
                ('Email', models.CharField(max_length=40)),
                ('Pais', models.CharField(max_length=10)),
                ('Contraseña', models.CharField(max_length=15)),
            ],
        ),
    ]
